 

import { NextResponse } from 'next/server';
 
import { promises as fsPromises } from 'fs';
 
 
// // SQL code generated by the OpenAI model
// const generatedSqlCode = `...`; // Replace with the generated SQL code

// // File path and name for the new .sql file
// const filePath = 'path/to/file.sql';

// async function createSqlFile() {
//   try {
//     await fsPromises.writeFile(filePath, generatedSqlCode);
//     console.log('.sql file created successfully.');
//   } catch (err) {
//     console.error('Error creating .sql file:', err);
//   }
// }




export async function POST(request:Request) {
  const  Code = await request.json();
  const generatedSqlCode = `${Code}`; // Replace with the generated SQL code
  
  // File path and name for the new .sql file
  const filePath = './schema.sql';


  try {
    await fsPromises.writeFile(filePath, generatedSqlCode);
    console.log('.sql file created successfully.');
  } catch (err) {
    console.error('Error creating .sql file:', err);
  }

  }

 
 