'use client'

import { Navbar } from '../components/Navbar'
import './globals.css'
import { Inter } from 'next/font/google'
import { UserProvider } from '@auth0/nextjs-auth0/client'
import { ReactNode } from 'react'
import { useUser } from '@auth0/nextjs-auth0/client'
import { Auth } from '@/components/auth'
import HomePage from '@/components/HomePage'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

type IndexProps = {
  children: ReactNode
}

export function Index({ children }: IndexProps) {
  const { user, error, isLoading } = useUser()
  console.log('user = ', user)

  if (user) {
    return (
      <div className=" container mx-auto">
        <Navbar />
        {children}
      </div>
    )
  } else {
    return (
      <>
        <Auth />
      </>
    )
  }
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <title>SQL GPT</title>
      </head>
      <UserProvider>
        <body className={inter.className}>
          <Index>{children}</Index>
        </body>
      </UserProvider>
    </html>
  )
}

{
  /* <>{children}</> */
}

{
  /* <link href="/Images/vercel.svg" sizes="180x180" /> */
}
